---
name: Run Selenium Cucumber Test

# Triger / Kapan Action-nya jalan
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest # windows-latest, macos-latest, ubuntu-18.04.

    steps:
      - uses: actions/checkout@v4 # Checkout the repository

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21' # Ganti dengan versi Java lain seperti '8', '17'
          distribution: 'temurin' # Alternatif: 'adoptopenjdk', 'zulu'
          cache: gradle # Cache agar build lebih cepat

      - name: Setup Chrome with extra capabilities
        uses: browser-actions/setup-chrome@v1.4.0
        with:
          chrome-version: latest # Ganti dengan 'stable' untuk versi stabil
          #chrome-options: '--headless' #(Jika ingin menjalankan Chrome dalam mode headless)

      - name: Build with Gradle
        run: |
          chmod +x gradlew  # Make gradlew executable
          ./gradlew build   # Run the build task before tests

      - name: Run Tests
        run: ./gradlew clean test # Run tests after the build step

      - name: Archive test results
        uses: actions/upload-artifact@v4.3.0
        if: always() # succes(), failure(), canceled()
        with:
          name: cucumber-reports
          path: build/reports/cucumber/cucumber.html # Path ke laporan Cucumber

        - name: Deploy Test Report to GitHub Pages
  if: always()
  uses: peaceiris/actions-gh-pages@v4.0.0
  with:
    personal_token: ${{ secrets.PAT }}
    publish_branch: gh-pages
    publish_dir: build/reports
    commit_message: "Deploy test report - ${{ github.sha }}"

