---
name: Run Selenium Cucumber Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write  # Pastikan bisa push hasil build jika perlu
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }} # Gunakan PAT jika butuh akses tambahan

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Chrome with extra capabilities
        uses: browser-actions/setup-chrome@v1.4.0
        with:
          chrome-version: latest

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Run Tests
        run: ./gradlew clean test

      - name: Archive test results
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: cucumber-reports
          path: build/reports/cucumber/cucumber.html
