name: Web UI Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    # Download Repositori
    - uses: actions/checkout@v3

    # Setup Java JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.2.3

    # Setup gradlew
    - name: Setup Gradlew
      run: chmod +x gradlew

    # Execute gradlew for running cucumber test
    - name: Execute test
      run: ./gradlew cucumber

    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Cucumber Report
        path: reports
        
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: target
