name: Web UI Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Download Repositori
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Java JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Install Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.3

      # Setup gradlew
      - name: Make Gradle Executable
        run: chmod +x gradlew

      # Execute gradlew for running cucumber test
      - name: Execute Web UI Tests
        run: ./gradlew cucumber


      # Archive Test Result
      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber Report
          path: build/reports/tests/test/

      # Deploy Cucumber Report to GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: build/reports/tests/test/
