name: Web UI Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
      # download repo
      - uses: actions/checkout@v3

      # setup java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # install browser
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0

      # setup gradlew
      - name: Setup gradlew
        run: chmod +x gradlew

      # execute gradle command for running cucumber test
      - name: Execute Test
        run: ./gradlew test

      # archive test result
      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber Report
          path : reports


      # 8️⃣ (Opsional) Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: build/reports
